<a href="https://colab.research.google.com/github/Aarushi900/Data_Mining/blob/main/Basics_of_pandas_and_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
arr=np.array([1,2,3,6,4,5])
reverse_arr_1=arr[::-1]
reverse_arr_2=np.flip(arr)
print(arr)
print(reverse_arr_1)
print(reverse_arr_2)

[1 2 3 6 4 5]
[5 4 6 3 2 1]
[5 4 6 3 2 1]


Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
#using flatten
flattened_array_1=array1.flatten()
#using ravel
flattened_array_2=array1.ravel()

print(array1)
print(flattened_array_1)
print(flattened_array_2)

[[1 2 3]
 [2 4 5]
 [1 2 3]]
[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
comp=arr1==arr2
print(comp)
print("overall")
print(comp.all())
#method 2
print("Method 2:")
if np.array_equal(arr1,arr2):
  print("Equal")
else:
   print("Not Equal")

[[ True  True]
 [ True  True]]
overall
True
Method 2:
Equal


Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
freq_val=np.bincount(x).argmax()
print(f"Most frequent element: {freq_val}")
print("Its indices are:")
for i in range(len(x)):
  if x[i]==freq_val:
    print(i)

Most frequent element: 1
Its indices are:
0
5
7
8
9


In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
freq_val=np.bincount(y).argmax()
print(f"Most frequent element: {freq_val}")
print("Its indices are:")
for i in range(len(y)):
  if y[i]==freq_val:
    print(i)

Most frequent element: 1
Its indices are:
0
1
2


For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise

In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum_all=gfg.sum()
print("sum of all elements ",sum_all)

sum of all elements  45


In [ ]:
sum_row=gfg.sum(axis=1)
print(sum_row)

[[14]
 [16]
 [15]]


In [ ]:
sum_col=gfg.sum(axis=0)
print(sum_col)

[[20  9 16]]


For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix

In [ ]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
sum_diagnol=np.trace(n_array)
print("Sum of diagnol elements(trace): ",sum_diagnol)

Sum of diagnol elements(trace):  176


In [ ]:
eigenvalue,eigenvector=np.linalg.eig(n_array)
print("Eigen values: ",eigenvalue)
print("Eigen vectors: ",eigenvector)

Eigen values:  [98.16835147 28.097044   49.73460452]
Eigen vectors:  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [ ]:
inverse_mat=np.linalg.inv(n_array)
print(inverse_mat)

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [ ]:
determinant=np.linalg.det(n_array)
print("Determinant of matrix: ",determinant)

Determinant of matrix:  137180.0000000001


Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]

q = [[4, 5], [6, 7]]


ii. p = [[1, 2], [2, 3], [4, 5]]

q = [[4, 5, 1], [6, 7, 2]]

In [4]:
p=np.array([[1,2],[2,3]])
q=np.array([[4,5],[6,7]])
pdt=np.dot(p,q)
print("Result of multiplication: ")
print(pdt)
covariance=np.cov(p.flatten(),q.flatten())
print("Covariance of the matrix:")
print(covariance)

Result of multiplication: 
[[16 19]
 [26 31]]
Covariance of the matrix:
[[0.66666667 1.        ]
 [1.         1.66666667]]


In [6]:
p=np.array([[1,2],[2,3],[4,5]])
q=np.array([[4,5,1],[6,7,2]])
pdt=np.dot(p,q)
print("Result of multiplication: ")
print(pdt)
covariance=np.cov(p.flatten(),q.flatten())
print("Covariance of the matrix: ")
print(covariance)

Result of multiplication: 
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance of the matrix: 
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [8]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
flattened_array = array.flatten()

In [9]:
absolute = np.abs(array)
print(absolute)

[[1 2 3]
 [4 5 6]]


In [14]:
mean_array = np.mean(flattened_array)
median_array = np.median(flattened_array)
std_dev_array = np.std(flattened_array)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_dev_col = np.std(array, axis=0)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_dev_row = np.std(array, axis=1)


print("\niii. Mean, Median, and Standard Deviation:")
print("Overall mean, median, and standard deviation:")
print("Mean:", mean_array)
print("Median:", median_array)
print("Standard Deviation:", std_dev_array)

print("\nColumn-wise mean, median, and standard deviation:")
print("Mean for each column:", mean_col)
print("Median for each column:", median_col)
print("Standard Deviation for each column:", std_dev_col)

print("\nRow-wise mean, median, and standard deviation:")
print("Mean for each row:", mean_row)
print("Median for each row:", median_row)
print("Standard Deviation for each row:", std_dev_row)


iii. Mean, Median, and Standard Deviation:
Overall mean, median, and standard deviation:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Column-wise mean, median, and standard deviation:
Mean for each column: [-1.5  1.5 -1.5]
Median for each column: [-1.5  1.5 -1.5]
Standard Deviation for each column: [2.5 3.5 4.5]

Row-wise mean, median, and standard deviation:
Mean for each row: [ 0.66666667 -1.66666667]
Median for each row: [ 1. -4.]
Standard Deviation for each row: [2.05480467 4.78423336]


In [13]:
percentile = np.percentile(flattened_array, q=[25,50,75])
percentile_row = np.percentile(array, q=[25,50,75],axis=1)
percentile_col = np.percentile(array, q=[25,50,75],axis=0)

print("\nii. Percentiles:")
print("Percentile for flattened array:")
print(percentile)
print("Percentiles for each column:")
print(percentile_col)
print("Percentiles for each row:")
print(percentile_row)


ii. Percentiles:
Percentile for flattened array:
[-3.5 -0.5  2.5]
Percentiles for each column:
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for each row:
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [15]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

In [17]:
ceil=np.ceil(a)
floor=np.floor(a)
trunc=np.trunc(a)
round=np.round(a)

print("Floor values: ")
print(floor)

print("Ceiling values: ")
print(ceil)

print("Truncated values: ")
print(trunc)

print("Rounded values: ")
print(round)

Floor values: 
[-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: 
[-1. -1. -0.  1.  2.  2.  3.]
Truncated values: 
[-1. -1. -0.  0.  1.  1.  3.]
Rounded values: 
[-2. -2. -0.  0.  2.  2.  3.]


For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements

In [18]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

In [19]:
sorted_a=np.sort(array)
print("Sorted Array: ",sorted_a)

Sorted Array:  [ 10  16  16  52  54  62 453]


In [21]:
sorted_indices=np.argsort(array)
print("Sorted array's indices: ",sorted_indices)

Sorted array's indices:  [0 3 4 1 5 2 6]


In [29]:
arr=[]
for i in range(0,4):
  arr.append(sorted_a[i])

for i in range(len(arr)):
  print(arr[i])

10
16
16
52


In [33]:
ar=[]

largest_indices = np.argpartition(array, -5)[-5:]

for i in largest_indices:
    ar.append(array[i])


for i in range(len(ar)):
  print(ar[i])

16
52
62
54
453


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only

ii. Float elements only

In [3]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

In [4]:
int_arr = array[array.astype(int) == array]
float_arr = array[array.astype(int) != array]

print("INTEGER ARRAY:")
for x in int_arr:
  print(x)

print("FLOAT ARRAY:")
for x in float_arr:
  print(x)

INTEGER ARRAY:
1.0
2.0
3.0
2.0
FLOAT ARRAY:
1.2
2.2


Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

Load the saved file into jupyter notebook?

In [7]:
from PIL import Image
import numpy as np

def img_to_array(path, output_file):
    # Read the image
    img = Image.open(path)

    # Convert the image to a NumPy array
    img_array = np.array(img)

    # Flatten the array for RGB images
    if len(img_array.shape) == 3:
        img_array = img_array.reshape(-1, img_array.shape[-1])

    # Save the array to a text file
    np.savetxt(output_file, img_array, fmt='%d')

# Example usage for a RGB image
img_to_array('/content/download.jpg', 'output_rgb.txt')

# Example usage for a grayscale image
img_to_array('/content/greyscale.jpg', 'output_grayscale.txt')


In [8]:
import numpy as np

# Load the saved file into a NumPy array
loaded_array_rgb = np.loadtxt('output_rgb.txt')
loaded_array_grayscale = np.loadtxt('output_grayscale.txt')

# Display the loaded arrays
print("Loaded RGB Array:")
print(loaded_array_rgb)

print("\nLoaded Grayscale Array:")
print(loaded_array_grayscale)


Loaded RGB Array:
[[60. 88. 89.]
 [59. 87. 88.]
 [57. 85. 86.]
 ...
 [ 0. 31. 38.]
 [ 0. 29. 36.]
 [ 0. 30. 38.]]

Loaded Grayscale Array:
[[172. 172. 172.]
 [166. 166. 166.]
 [153. 153. 153.]
 ...
 [188. 188. 188.]
 [188. 188. 188.]
 [189. 189. 189.]]
